### ISSUE TITLE
`to_radians` and `to_degrees` methods cause loss of the derivative 

### ISSUE THREAD

**Issue by paveloom** [elrnv/autodiff#2]
Current implementation:

https://github.com/elrnv/autodiff/blob/a5d46e680ffcaf0b9eba891de7bdbe4fdbe24e10/src/forward_autodiff.rs#L1279-L1286

Seems like changing it to proper implementations should be straightforward:
 - [`to_radians`](https://doc.rust-lang.org/src/core/num/f64.rs.html#739)
 - [`to_degrees`](https://doc.rust-lang.org/src/core/num/f64.rs.html#719)

**Comment by elrnv** [comment]
I absolutely agree thanks for the catch!
