### ISSUE TITLE
Hello! I'm also working on automatic differentiation crate

### ISSUE THREAD

**Issue by djmaxus** [elrnv/autodiff#3]
Hi, my name is Max.
I do academic research on Reduced Order Modeling of dynamical systems
and somewhat related developments for a company.

I could not find another ways to contact you, so this will be my 'email' 😃 

This summer I started learning Rust and making automatic differentiation as my first project in that language.

So it was barely possible to miss your crate `autodiff`, which I was glad to have a look at.

For me, it's a pleasure to meet people 
with your background and expertise by accident.

My crate is called [`autodj`](https://crates.io/crates/autodj).
I would be glad for your feedback on it in case that's possible.

Best wishes,

Maksim Elizarev
[djmaxus.github.io](https://djmaxus.github.io/)

**Comment by elrnv** [comment]
Hi Max!

Thanks for your "email" :)
You can often find emails of authors in `Cargo.toml` files in Rust projects, and in git commit history by running `git log` on a project.

I like your crate, and thank you for your contribution to scientific computing in Rust!
There are a number of other automatic differentiation libraries (e.g. [hyperdual](https://crates.io/crates/hyperdual/) and [Fwd:AD](https://crates.io/crates/fwd_ad)) that have implemented more feature-full alternatives to autodiff, especially when it comes to multivariate automatic differentiation.

In this space I would personally love to see more benchmarks and efficient implementations of reverse-mode automatic differentiation. I think these can help guide future development in this area.

Best,
Egor
